name       : opencascade-ce
version    : 0.18.3
release    : 5
source     :
    - https://github.com/tpaviot/oce/archive/OCE-0.18.3.tar.gz : c553d6a7bf52f790abc3b6bb7a1e91a65947e92a426bb1a88a11960c31f0966c
license    : LGPL-2.1-or-later WITH OCCT-exception-1.0
component  : programming
summary    : opencascade community edition
description: |
    A 3D modeling kernel that consists of reusable C++ object libraries that are available as Open Source.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(x11)
patterns   :
    - devel :
        - /usr/lib64/*/*.cmake
setup      : |
    %cmake -DOCE_INSTALL_PREFIX:PATH=/usr \
           -DOCE_BUILD_SHARED_LIB=TRUE \
           -DOCE_INSTALL_LIB_DIR:PATH=%libdir% \
           -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
