name       : opencascade-ce
version    : 0.17.2
release    : 2
source     :
    - https://github.com/tpaviot/oce/archive/OCE-0.17.2.tar.gz : 8d9995360cd531cbd4a7aa4ca5ed969f08ec7c7a37755e2f3d4ef832c1b2f56e
license    : LGPL-2.1-with-OCCT-exception-1.0
component  : programming
summary    : opencascade community edition
description: |
    A 3D modeling kernel that consists of reusable C++ object libraries that are available as Open Source.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - VTK-devel
patterns:
    - devel :
        - /usr/lib64/*/*.cmake
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-for-glibc-226.patch
    %cmake -DOCE_INSTALL_PREFIX:PATH=/usr -DOCE_BUILD_SHARED_LIB=TRUE -DOCE_INSTALL_LIB_DIR:PATH=%libdir% -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
