name       : opencascade
version    : 7.6.1
release    : 8
source     :
    - https://gitlab.com/blobfish/occt/-/archive/V7_6_1/occt-V7_6_1.tar.gz : c111c635fa4cae05821640f5afbbf362efaee8dc51fcbee953866eec7482cd6a
homepage   : https://www.opencascade.org
license    : LGPL-2.1-only WITH OCCT-exception-1.0
component  : programming
summary    : Development platform for CAD/CAE, 3D surface/solid modeling and data exchange
description: |
    Open CASCADE Technology (OCCT) is a 3D modeling kernel that consists of reusable C++ object libraries that are available as Open Source.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(tk)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - VTK-devel
    - freeimage-devel
replaces   :
    - opencascade-ce
    - devel :
        - opencascade-ce-devel
setup      : |
    %apply_patches
    export DESTDIR=$installdir
    %cmake_ninja \
        -DBUILD_RELEASE_DISABLE_EXCEPTIONS=OFF \
        -DINSTALL_SAMPLES=ON \
        -DINSTALL_TEST_CASES=OFF \
        -DINSTALL_DIR_LIB=lib64 \
        -DLIB_SUFFIX=64 \
        -DUSE_D3D=OFF \
        -DUSE_FFMPEG=ON \
        -DUSE_FREEIMAGE=ON \
        -DUSE_FREETYPE=ON \
        -DUSE_RAPIDJSON=ON \
        -DUSE_TBB=ON \
        -DUSE_VTK=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/bin/*.sh
    rm -rf $installdir/usr/share/doc
#check      : |
    #%ninja_check
